// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Čajevi.Models;

namespace Čajevi.Migrations
{
    [DbContext(typeof(čajeviContext))]
    [Migration("20190914140409_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Čajevi.Models.Biljni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("godina");

                    b.Property<string>("ime")
                        .IsRequired();

                    b.Property<float>("kilaza");

                    b.Property<int>("komada");

                    b.Property<string>("podrijetlo")
                        .IsRequired();

                    b.Property<string>("vrsta")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Biljni");
                });

            modelBuilder.Entity("Čajevi.Models.Premium", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("godina");

                    b.Property<string>("ime")
                        .IsRequired();

                    b.Property<float>("kilaza");

                    b.Property<int>("komada");

                    b.Property<string>("podrijetlo")
                        .IsRequired();

                    b.Property<string>("vrsta")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Premium");
                });

            modelBuilder.Entity("Čajevi.Models.SpecialEdition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("godina");

                    b.Property<string>("ime")
                        .IsRequired();

                    b.Property<float>("kilaza");

                    b.Property<int>("komada");

                    b.Property<string>("podrijetlo")
                        .IsRequired();

                    b.Property<string>("vrsta")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SpecialEdition");
                });

            modelBuilder.Entity("Čajevi.Models.Voćni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("godina");

                    b.Property<string>("ime")
                        .IsRequired();

                    b.Property<float>("kilaza");

                    b.Property<int>("komada");

                    b.Property<string>("podrijetlo")
                        .IsRequired();

                    b.Property<string>("vrsta")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Voćni");
                });
#pragma warning restore 612, 618
        }
    }
}
